In [1]:
from pathlib import Path
image_folder_synthetic = Path(r"/home/vsarasani/Ray-Verify-/Data/all_synthetic_images")
print("Folder found:", image_folder_synthetic.is_dir())

Folder found: True

In [2]:
from PIL import Image

images = []
valid_paths = []
failed_files = []

for path in image_folder_synthetic.rglob("*"):
    if path.is_file() and path.suffix.lower() in {
        ".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"
    }:
        try:
            with Image.open(path) as img:
                images.append(img.copy())
            valid_paths.append(path)

        except OSError:
            failed_files.append(path)
            print("Cannot read:", path.name)

print("Images loaded:", len(images))
print("Unreadable files:", len(failed_files))

Images loaded: 6289
Unreadable files: 0

In [3]:
from pathlib import Path
image_folder_patient = Path(r"/home/vsarasani/Ray-Verify-/Data/patient acquired")
print("Folder found:", image_folder_patient.is_dir())

Folder found: True

In [4]:
from PIL import Image
images = []
for path in image_folder_patient.rglob("*"):
    if path.is_file() and path.suffix.lower() in {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"}:
        with Image.open(path) as img:
            images.append(img.copy())

print("Images loaded:", len(images))

Images loaded: 6319

Inspecting patient acquired data

In [5]:
import numpy as np
import pandas as pd
patient_folder = Path(
    "/home/vsarasani/Ray-Verify-/Data/patient acquired"
)

if not patient_folder.is_dir():
    raise FileNotFoundError(f"Folder not found: {patient_folder}")

patient_records = []
failed_files = []

for path in sorted(patient_folder.rglob("*")):
    if path.is_file() and path.suffix.lower() in {
        ".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"
    }:
        try:
            with Image.open(path) as img:
                pixels = np.asarray(img)

                patient_records.append({
                    "image_number": len(patient_records) + 1,
                    "filename": path.name,
                    "width": img.width,
                    "height": img.height,
                    "channels": len(img.getbands()),
                    "mode": img.mode,
                    "pixel_data_type": str(pixels.dtype),
                    "pixel_values": pixels.size
                })
        except OSError as error:
            failed_files.append(str(path))
            print("Cannot read:", path.name)

patient_image_info = pd.DataFrame(patient_records)

print("Patient-acquired images read:", len(patient_image_info))
print("Failed files:", len(failed_files))
print("Features per image = width × height × channels")

display(patient_image_info.head())
display(patient_image_info.dtypes)

Patient-acquired images read: 6319
Failed files: 0
Features per image = width × height × channels

,image_number,filename,width,height,channels,mode,pixel_data_type,pixel_values
0,1,0005e8e3701dfb1dd93d53e2ff537b6e-checkpoint.png,256,256,1,L,uint8,65536
1,2,0006e0a85696f6bb578e84fafa9a5607.png,256,256,1,L,uint8,65536
2,3,0007d316f756b3fa0baea2ff514ce945.png,256,256,1,L,uint8,65536
3,4,0021df30f3fddef551eb3df4354b1d06.png,256,256,1,L,uint8,65536
4,5,002a34c58c5b758217ed1f584ccbcfe9.png,256,256,1,L,uint8,65536

image_number        int64
filename           object
width               int64
height              int64
channels            int64
mode               object
pixel_data_type    object
pixel_values        int64
dtype: object

Inspecting Synthetic ai data

In [6]:

synthetic_folder = Path(
    "/home/vsarasani/Ray-Verify-/Data/all_synthetic_images"
)

if not synthetic_folder.is_dir():
    raise FileNotFoundError(f"Folder not found: {synthetic_folder}")

synthetic_records = []
failed_files = []

for path in sorted(synthetic_folder.rglob("*")):
    if path.is_file() and path.suffix.lower() in {
        ".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"
    }:
        try:
            with Image.open(path) as img:
                pixels = np.asarray(img)

                synthetic_records.append({
                    "image_number": len(synthetic_records) + 1,
                    "filename": path.name,
                    "width": img.width,
                    "height": img.height,
                    "channels": len(img.getbands()),
                    "mode": img.mode,
                    "pixel_data_type": str(pixels.dtype),
                    "pixel_values": pixels.size
                })
        except OSError as error:
            failed_files.append(str(path))
            print("Cannot read:", path.name)

synthetic_image_info = pd.DataFrame(synthetic_records)

print("Synthetic-acquired images read:", len(synthetic_image_info))
print("Failed files:", len(failed_files))
print("Features per image = width × height × channels")

display(synthetic_image_info.head())
display(synthetic_image_info.dtypes)

Synthetic-acquired images read: 6289
Failed files: 0
Features per image = width × height × channels

,image_number,filename,width,height,channels,mode,pixel_data_type,pixel_values
0,1,00001_COVID19(10)-checkpoint-checkpoint.jpg,1038,1031,3,RGB,uint8,3210534
1,2,00001_COVID19(10)-checkpoint-checkpoint.png,256,256,1,L,uint8,65536
2,3,00002_person107_virus_197-checkpoint.png,256,256,1,L,uint8,65536
3,4,00003_person10_bacteria_43-checkpoint.png,256,256,1,L,uint8,65536
4,5,00004_COVID19(0).png,256,256,1,L,uint8,65536

image_number        int64
filename           object
width               int64
height              int64
channels            int64
mode               object
pixel_data_type    object
pixel_values        int64
dtype: object

Creating .gitignore file

In [7]:
from pathlib import Path

gitignore = Path(".gitignore")

with gitignore.open("a") as file:
    file.write("\ndata/\n")

print("Created at:", gitignore.resolve())

Created at: /home/vsarasani/Ray-Verify-/.gitignore

In [8]:
from pathlib import Path
file = Path(".gitignore")
print("Exists:", file.is_file())
print("Contents:", file.read_text())

Exists: True
Contents:
data/

data/

data/

data/

data/

data/

PREPROCESS AND DATA CLEANING

Transforming JPEG files in synthetic data to PNG

In [9]:
image_folder = Path("Data/all_synthetic_images")

print("Folder found:", image_folder.is_dir())

Folder found: True

Converting JPG to PNG

In [10]:
from pathlib import Path
from PIL import Image

image_folder = Path("Data/all_synthetic_images")  

count = 0

for path in image_folder.iterdir():
    if path.suffix.lower() in {".jpg", ".jpeg"}:
        png_path = path.with_suffix(".png")

        if png_path.exists():
            print("Skipped — PNG already exists:", path.name)
            continue

        with Image.open(path) as img:
            img.save(png_path, format="PNG")

        path.unlink()  
        count += 1

print("JPEG files replaced with PNG:", count)

JPEG files replaced with PNG: 0

2110 files were in jpg form, converted all and run the cell again to make sure none are left. That is the reason it is showing 0 files converted.

Converting the Synthetic ai images to grayscale and with same number of pixels as patient- acquired.

In [11]:
from pathlib import Path
from PIL import Image, ImageOps

image_folder = Path("/home/vsarasani/Ray-Verify-/Data/all_synthetic_images")

count = 0

for path in image_folder.iterdir():
    if path.is_file() and path.suffix.lower() == ".png":
        with Image.open(path) as img:
            img = img.convert("L")  

            # Resize without stretching; add black padding if needed
            img = ImageOps.pad(
                img,
                (256, 256),
                method=Image.Resampling.LANCZOS,
                color=0
            )

        img.save(path, format="PNG")
        count += 1

print("Images resized:", count)
print("Size: 256 × 256")
print("Channels: 1 (grayscale)")
print("Pixel values per image:", 256 * 256)

Images resized: 6287
Size: 256 × 256
Channels: 1 (grayscale)
Pixel values per image: 65536

All images are now in grayscale,same dimensions, same format and same pixel values.

Deleting duplicate images

In [12]:
from pathlib import Path
from PIL import Image
import hashlib

image_folder = Path("/home/vsarasani/Ray-Verify-/Data/all_synthetic_images")

seen = {}
duplicates = []
failed_files = []

for path in sorted(image_folder.rglob("*")):
    if not path.is_file() or path.suffix.lower() not in {".png", ".jpg", ".jpeg"}:
        continue

    try:
        with Image.open(path) as img:
            img = img.convert("RGB")
            image_hash = hashlib.sha256(
                str(img.size).encode() + img.tobytes()
            ).hexdigest()

        if image_hash in seen:
            duplicates.append((seen[image_hash], path))
        else:
            seen[image_hash] = path

    except OSError:
        failed_files.append(path)
        print("Cannot read:", path.name)

print("Extra duplicate copies:", len(duplicates))
print("Unreadable files:", len(failed_files))

for original, duplicate in duplicates:
    print("\nFirst copy:", original)
    print("Duplicate: ", duplicate)

Extra duplicate copies: 0
Unreadable files: 0

In [13]:
deleted = 0

for original, duplicate in duplicates:
    if original.exists() and duplicate.exists() and original != duplicate:
        duplicate.unlink()
        print("Deleted:", duplicate.name)
        deleted += 1

print("Duplicate copies deleted:", deleted)

Duplicate copies deleted: 0

In [14]:
from pathlib import Path
from PIL import Image
import hashlib

image_folder = Path("/home/vsarasani/Ray-Verify-/Data/patient acquired")

seen = {}
duplicates = []
failed_files = []

for path in sorted(image_folder.rglob("*")):
    if not path.is_file() or path.suffix.lower() not in {".png", ".jpg", ".jpeg"}:
        continue

    try:
        with Image.open(path) as img:
            img = img.convert("RGB")
            image_hash = hashlib.sha256(
                str(img.size).encode() + img.tobytes()
            ).hexdigest()

        if image_hash in seen:
            duplicates.append((seen[image_hash], path))
        else:
            seen[image_hash] = path

    except OSError:
        failed_files.append(path)
        print("Cannot read:", path.name)

print("Extra duplicate copies:", len(duplicates))
print("Unreadable files:", len(failed_files))

for original, duplicate in duplicates:
    print("\nFirst copy:", original)
    print("Duplicate: ", duplicate)

Extra duplicate copies: 0
Unreadable files: 0

Deleted all duplicate values.

Creating a .csv metadata file

In [20]:
from pathlib import Path
from PIL import Image
import pandas as pd

base = Path("/home/vsarasani/Ray-Verify-/Data")

sources = [
    (
        base / "patient acquired",
        "patient-acquired",
        "https://www.kaggle.com/datasets/xhlulu/vinbigdata-chest-xray-resized-png-256x256"
    ),
    (
        base / "all_synthetic_images",
        "synthetic",
        "https://www.kaggle.com/code/farihabintasadeque/synthetic-chestxrays/input?select=train"
    )
]

rows = []

for folder, label, source_url in sources:
    if not folder.is_dir():
        raise FileNotFoundError(f"Folder not found: {folder}")

    for path in sorted(folder.rglob("*")):
        if not path.is_file() or path.suffix.lower() not in {
            ".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"
        }:
            continue

        processing_state = "unknown"
        quality_status = "unreadable"

        try:
            with Image.open(path) as img:
                img.load()
                processing_state = (
                    f"{img.format}; {img.width}x{img.height}; mode={img.mode}"
                )
                quality_status = "readable; duplicates not checked here"
        except OSError:
            pass

        rows.append({
            "image_path": str(path.relative_to(base)),
            "source_url": source_url,
            "download_date": "10-03-2026",
            "origin_label": label,
            "label_status": "provisional",
            "provenance_evidence": "unknown",
            "processing_state": processing_state,
            "quality_status": quality_status,
        })

metadata = pd.DataFrame(rows)

output = base / "image_metadata.csv"
metadata.to_csv(output, index=False)

print("Images recorded:", len(metadata))
print("Saved to:", output)
display(metadata.head())

Images recorded: 12608
Saved to: /home/vsarasani/Ray-Verify-/Data/image_metadata.csv

,image_path,source_url,download_date,origin_label,label_status,provenance_evidence,processing_state,quality_status
0,patient acquired/.ipynb_checkpoints/0005e8e370...,https://www.kaggle.com/datasets/xhlulu/vinbigd...,10-03-2026,patient-acquired,provisional,unknown,PNG; 256x256; mode=L,readable; duplicates not checked here
1,patient acquired/0006e0a85696f6bb578e84fafa9a5...,https://www.kaggle.com/datasets/xhlulu/vinbigd...,10-03-2026,patient-acquired,provisional,unknown,PNG; 256x256; mode=L,readable; duplicates not checked here
2,patient acquired/0007d316f756b3fa0baea2ff514ce...,https://www.kaggle.com/datasets/xhlulu/vinbigd...,10-03-2026,patient-acquired,provisional,unknown,PNG; 256x256; mode=L,readable; duplicates not checked here
3,patient acquired/0021df30f3fddef551eb3df4354b1...,https://www.kaggle.com/datasets/xhlulu/vinbigd...,10-03-2026,patient-acquired,provisional,unknown,PNG; 256x256; mode=L,readable; duplicates not checked here
4,patient acquired/002a34c58c5b758217ed1f584ccbc...,https://www.kaggle.com/datasets/xhlulu/vinbigd...,10-03-2026,patient-acquired,provisional,unknown,PNG; 256x256; mode=L,readable; duplicates not checked here

Splitting testing data

In [15]:
from sklearn.model_selection import train_test_split

patient_files = sorted(
    Path("/home/vsarasani/Ray-Verify-/Data/patient acquired").glob("*.png")
)

synthetic_files = sorted(
    Path("/home/vsarasani/Ray-Verify-/Data/all_synthetic_images").glob("*.png")
)

X = patient_files + synthetic_files
y = [0] * len(patient_files) + [1] * len(synthetic_files)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

Splitting validation data with data augmentation and normalization

In [17]:
from PIL import Image, ImageEnhance

rng = np.random.default_rng(42)

def prepare_image(path, augment=False):
    with Image.open(path) as img:
        img = img.convert("L")

        if img.size != (256, 256):
            raise ValueError(f"Image must be 256 × 256: {path}")

        if augment:
            factor = rng.uniform(0.95, 1.05)
            img = ImageEnhance.Brightness(img).enhance(factor)

        return np.asarray(img, dtype=np.float32) / 255.0

In [18]:
import numpy as np
from sklearn.model_selection import StratifiedKFold

X_pool = np.array(X_train)
y_pool = np.array(y_train)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for fold, (train_idx, val_idx) in enumerate(cv.split(X_pool, y_pool), 1):
    X_fold_train = X_pool[train_idx]
    X_fold_val = X_pool[val_idx]
    y_fold_train = y_pool[train_idx]
    y_fold_val = y_pool[val_idx]

    # Augment and normalize this fold's training images
    train_pixels = np.empty(
        (len(X_fold_train), 256, 256),
        dtype=np.float32
    )

    for i, path in enumerate(X_fold_train):
        train_pixels[i] = prepare_image(path, augment=True)

    print(f"Fold {fold}: {len(train_pixels)} training images processed")


    del train_pixels

Fold 1: 8067 training images processed
Fold 2: 8067 training images processed
Fold 3: 8067 training images processed
Fold 4: 8067 training images processed
Fold 5: 8068 training images processed

Augmentation and Normalization is done for all training data.